window.env = {
  "TERM_PROGRAM": "vscode",
  "NODE": "/usr/local/bin/node",
  "INIT_CWD": "/Users/mtxuser/Documents/React/react-youtube-app",
  "SHELL": "/bin/zsh",
  "TERM": "xterm-256color",
  "TMPDIR": "/var/folders/y6/y405d9rx66xfjx9gbhh1mbxw0000gp/T/",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "TERM_PROGRAM_VERSION": "1.55.2",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "COLOR": "1",
  "npm_config_noproxy": "",
  "USER": "Kartikmishra",
  "COMMAND_MODE": "unix2003",
  "npm_config_globalconfig": "/usr/local/etc/npmrc",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.ZCm4XsOzdk/Listeners",
  "__CF_USER_TEXT_ENCODING": "0x1F6:0x0:0x0",
  "npm_execpath": "/usr/local/lib/node_modules/npm/bin/npm-cli.js",
  "PATH": "/Users/mtxuser/Documents/React/react-youtube-app/node_modules/.bin:/Users/mtxuser/Documents/React/node_modules/.bin:/Users/mtxuser/Documents/node_modules/.bin:/Users/mtxuser/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/Users/mtxuser/Documents/React/react-youtube-app/node_modules/.bin:/Users/mtxuser/Documents/React/node_modules/.bin:/Users/mtxuser/Documents/node_modules/.bin:/Users/mtxuser/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/Users/mtxuser/Downloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/mtxuser/Downloads/google-cloud-sdk/bin",
  "_": "/Users/mtxuser/Documents/React/react-youtube-app/node_modules/.bin/react-dotenv",
  "npm_package_json": "/Users/mtxuser/Documents/React/react-youtube-app/package.json",
  "__CFBundleIdentifier": "com.microsoft.VSCode",
  "npm_config_init_module": "/Users/mtxuser/.npm-init.js",
  "npm_config_userconfig": "/Users/mtxuser/.npmrc",
  "PWD": "/Users/mtxuser/Documents/React/react-youtube-app",
  "npm_command": "run-script",
  "EDITOR": "vi",
  "npm_lifecycle_event": "build",
  "LANG": "en_GB.UTF-8",
  "npm_package_name": "react-youtube-app",
  "XPC_FLAGS": "0x0",
  "npm_config_node_gyp": "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "XPC_SERVICE_NAME": "0",
  "npm_package_version": "0.1.0",
  "HOME": "/Users/mtxuser",
  "SHLVL": "3",
  "VSCODE_GIT_ASKPASS_MAIN": "/private/var/folders/y6/y405d9rx66xfjx9gbhh1mbxw0000gp/T/AppTranslocation/E6BB10C7-0C98-497D-80C9-EC4C302C52CA/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
  "LOGNAME": "Kartikmishra",
  "npm_config_cache": "/Users/mtxuser/.npm",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "VSCODE_GIT_IPC_HANDLE": "/var/folders/y6/y405d9rx66xfjx9gbhh1mbxw0000gp/T/vscode-git-66c4706bc9.sock",
  "npm_config_user_agent": "npm/7.16.0 node/v14.16.1 darwin x64 workspaces/false",
  "GIT_ASKPASS": "/private/var/folders/y6/y405d9rx66xfjx9gbhh1mbxw0000gp/T/AppTranslocation/E6BB10C7-0C98-497D-80C9-EC4C302C52CA/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
  "VSCODE_GIT_ASKPASS_NODE": "/private/var/folders/y6/y405d9rx66xfjx9gbhh1mbxw0000gp/T/AppTranslocation/E6BB10C7-0C98-497D-80C9-EC4C302C52CA/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Renderer).app/Contents/MacOS/Code Helper (Renderer)",
  "COLORTERM": "truecolor",
  "npm_config_prefix": "/usr/local",
  "npm_node_execpath": "/usr/local/bin/node",
  "YOUTUBE_API_KEY": "AIzaSyAK_6kdnbG6BXopoIYWrmXm20RaDjef02I"
};